# Generated by Django 3.1.2 on 2020-10-22 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='captured_images',
            old_name='name',
            new_name='user_name',
        ),
    ]
